// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8cpOjABwcN7mEOvtuNI1FwV-3-3BDKk0',
    appId: '1:995514231101:web:97f154df88d151c54efd54',
    messagingSenderId: '995514231101',
    projectId: 'nckh-1ec7b',
    authDomain: 'nckh-1ec7b.firebaseapp.com',
    databaseURL: 'https://nckh-1ec7b-default-rtdb.firebaseio.com',
    storageBucket: 'nckh-1ec7b.appspot.com',
    measurementId: 'G-FYSJV2W4EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1mXhbUrEPY6xgwYQS6w5tNS93Y_L51es',
    appId: '1:995514231101:android:610b2db5cd4bf87b4efd54',
    messagingSenderId: '995514231101',
    projectId: 'nckh-1ec7b',
    databaseURL: 'https://nckh-1ec7b-default-rtdb.firebaseio.com',
    storageBucket: 'nckh-1ec7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkmWSzAxzX0oNzQjBecGjXiMdmroryR4w',
    appId: '1:995514231101:ios:24e25899cb2a40054efd54',
    messagingSenderId: '995514231101',
    projectId: 'nckh-1ec7b',
    databaseURL: 'https://nckh-1ec7b-default-rtdb.firebaseio.com',
    storageBucket: 'nckh-1ec7b.appspot.com',
    androidClientId: '995514231101-1s3m63bcie4drqqfjb1j4jgcmf02aaqg.apps.googleusercontent.com',
    iosClientId: '995514231101-mfhusk1fhlae691s12an71mnf456alli.apps.googleusercontent.com',
    iosBundleId: 'com.example.appiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkmWSzAxzX0oNzQjBecGjXiMdmroryR4w',
    appId: '1:995514231101:ios:24e25899cb2a40054efd54',
    messagingSenderId: '995514231101',
    projectId: 'nckh-1ec7b',
    databaseURL: 'https://nckh-1ec7b-default-rtdb.firebaseio.com',
    storageBucket: 'nckh-1ec7b.appspot.com',
    androidClientId: '995514231101-1s3m63bcie4drqqfjb1j4jgcmf02aaqg.apps.googleusercontent.com',
    iosClientId: '995514231101-mfhusk1fhlae691s12an71mnf456alli.apps.googleusercontent.com',
    iosBundleId: 'com.example.appiot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8cpOjABwcN7mEOvtuNI1FwV-3-3BDKk0',
    appId: '1:995514231101:web:45e84936993b98574efd54',
    messagingSenderId: '995514231101',
    projectId: 'nckh-1ec7b',
    authDomain: 'nckh-1ec7b.firebaseapp.com',
    databaseURL: 'https://nckh-1ec7b-default-rtdb.firebaseio.com',
    storageBucket: 'nckh-1ec7b.appspot.com',
    measurementId: 'G-J6GXMDEEKE',
  );

}